### ISSUE TITLE
When will you release the trained model?

### ISSUE THREAD

**Issue by kekezhang112** [weizhou-geek/DeepSRQ#2]
Hi, 

Thank you for your great work!
Could you please release your trained model?

**Comment by weizhou-geek** [comment]
> Hi,
> 
> Thank you for your great work!
> Could you please release your trained model?

Hi,

Thanks for your interest in our work. I've searched and uploaded the model trained on SRID database.

Hope it helps.

Thanks,
Wei

**Comment by kekezhang112** [comment]
> > Hi,
> > Thank you for your great work!
> > Could you please release your trained model?
> 
> Hi,
> 
> Thanks for your interest in our work. I've searched and uploaded the model trained on SRID database.
> 
> Hope it helps.
> 
> Thanks,
> Wei

Thank you very much!

Best,
Keke
